# Generated by Django 5.0.2 on 2024-07-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_encuestas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='fecha_publicación',
            new_name='fecha_publicacion',
        ),
    ]
